//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.01.21 at 06:00:16 PM MSK 
//


package com.ediweb.education.protocol;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Protocol-Type"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="SXBP"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Protocol-Version"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="1"/&gt;
 *                         &lt;maxInclusive value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Method"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="CONNECT"/&gt;
 *                         &lt;enumeration value="FIND"/&gt;
 *                         &lt;enumeration value="CREATE"/&gt;
 *                         &lt;enumeration value="UPDATE"/&gt;
 *                         &lt;enumeration value="DELETE"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="URI"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="256"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Status-Code"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="1"/&gt;
 *                         &lt;maxInclusive value="1000"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Reason-Phrase" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Server" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Content-Encoding"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="UTF-8"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Content-Language"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="EN"/&gt;
 *                         &lt;enumeration value="RU"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Content-Type"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="text/xml"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="User-Agent"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="SSC"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Content"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="Documents"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="Document" maxOccurs="unbounded"&gt;
 *                                           &lt;complexType&gt;
 *                                             &lt;complexContent&gt;
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                 &lt;sequence&gt;
 *                                                   &lt;element name="File-Name"&gt;
 *                                                     &lt;simpleType&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                         &lt;maxLength value="256"/&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/simpleType&gt;
 *                                                   &lt;/element&gt;
 *                                                   &lt;element name="Content-Path"&gt;
 *                                                     &lt;simpleType&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                         &lt;maxLength value="256"/&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/simpleType&gt;
 *                                                   &lt;/element&gt;
 *                                                   &lt;element name="Check-Sum"&gt;
 *                                                     &lt;simpleType&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                         &lt;minLength value="64"/&gt;
 *                                                         &lt;maxLength value="64"/&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/simpleType&gt;
 *                                                   &lt;/element&gt;
 *                                                   &lt;element name="Check-Sum-Type"&gt;
 *                                                     &lt;simpleType&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                         &lt;enumeration value="SHA-256"/&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/simpleType&gt;
 *                                                   &lt;/element&gt;
 *                                                 &lt;/sequence&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/complexContent&gt;
 *                                           &lt;/complexType&gt;
 *                                         &lt;/element&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "body"
})
@XmlRootElement(name = "Message")
public class Message {

    @XmlElement(name = "Header", required = true)
    protected Message.Header header;
    @XmlElement(name = "Body", required = true)
    protected Message.Body body;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is
     * {@link Message.Header }
     */
    public Message.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is
     *              {@link Message.Header }
     */
    public void setHeader(Message.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return possible object is
     * {@link Message.Body }
     */
    public Message.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value allowed object is
     *              {@link Message.Body }
     */
    public void setBody(Message.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Content"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="Documents"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="Document" maxOccurs="unbounded"&gt;
     *                                 &lt;complexType&gt;
     *                                   &lt;complexContent&gt;
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                       &lt;sequence&gt;
     *                                         &lt;element name="File-Name"&gt;
     *                                           &lt;simpleType&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                               &lt;maxLength value="256"/&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/simpleType&gt;
     *                                         &lt;/element&gt;
     *                                         &lt;element name="Content-Path"&gt;
     *                                           &lt;simpleType&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                               &lt;maxLength value="256"/&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/simpleType&gt;
     *                                         &lt;/element&gt;
     *                                         &lt;element name="Check-Sum"&gt;
     *                                           &lt;simpleType&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                               &lt;minLength value="64"/&gt;
     *                                               &lt;maxLength value="64"/&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/simpleType&gt;
     *                                         &lt;/element&gt;
     *                                         &lt;element name="Check-Sum-Type"&gt;
     *                                           &lt;simpleType&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                               &lt;enumeration value="SHA-256"/&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/simpleType&gt;
     *                                         &lt;/element&gt;
     *                                       &lt;/sequence&gt;
     *                                     &lt;/restriction&gt;
     *                                   &lt;/complexContent&gt;
     *                                 &lt;/complexType&gt;
     *                               &lt;/element&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "content"
    })
    public static class Body {

        @XmlElement(name = "Content", required = true)
        protected Message.Body.Content content;

        /**
         * Gets the value of the content property.
         *
         * @return possible object is
         * {@link Message.Body.Content }
         */
        public Message.Body.Content getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value allowed object is
         *              {@link Message.Body.Content }
         */
        public void setContent(Message.Body.Content value) {
            this.content = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected         content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="Documents"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="Document" maxOccurs="unbounded"&gt;
         *                       &lt;complexType&gt;
         *                         &lt;complexContent&gt;
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                             &lt;sequence&gt;
         *                               &lt;element name="File-Name"&gt;
         *                                 &lt;simpleType&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                                     &lt;maxLength value="256"/&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/simpleType&gt;
         *                               &lt;/element&gt;
         *                               &lt;element name="Content-Path"&gt;
         *                                 &lt;simpleType&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                                     &lt;maxLength value="256"/&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/simpleType&gt;
         *                               &lt;/element&gt;
         *                               &lt;element name="Check-Sum"&gt;
         *                                 &lt;simpleType&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                                     &lt;minLength value="64"/&gt;
         *                                     &lt;maxLength value="64"/&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/simpleType&gt;
         *                               &lt;/element&gt;
         *                               &lt;element name="Check-Sum-Type"&gt;
         *                                 &lt;simpleType&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                                     &lt;enumeration value="SHA-256"/&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/simpleType&gt;
         *                               &lt;/element&gt;
         *                             &lt;/sequence&gt;
         *                           &lt;/restriction&gt;
         *                         &lt;/complexContent&gt;
         *                       &lt;/complexType&gt;
         *                     &lt;/element&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "documents"
        })
        public static class Content {

            @XmlElement(name = "Documents", required = true)
            protected Message.Body.Content.Documents documents;

            /**
             * Gets the value of the documents property.
             *
             * @return possible object is
             * {@link Message.Body.Content.Documents }
             */
            public Message.Body.Content.Documents getDocuments() {
                return documents;
            }

            /**
             * Sets the value of the documents property.
             *
             * @param value allowed object is
             *              {@link Message.Body.Content.Documents }
             */
            public void setDocuments(Message.Body.Content.Documents value) {
                this.documents = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected         content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Document" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="File-Name"&gt;
             *                     &lt;simpleType&gt;
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *                         &lt;maxLength value="256"/&gt;
             *                       &lt;/restriction&gt;
             *                     &lt;/simpleType&gt;
             *                   &lt;/element&gt;
             *                   &lt;element name="Content-Path"&gt;
             *                     &lt;simpleType&gt;
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *                         &lt;maxLength value="256"/&gt;
             *                       &lt;/restriction&gt;
             *                     &lt;/simpleType&gt;
             *                   &lt;/element&gt;
             *                   &lt;element name="Check-Sum"&gt;
             *                     &lt;simpleType&gt;
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *                         &lt;minLength value="64"/&gt;
             *                         &lt;maxLength value="64"/&gt;
             *                       &lt;/restriction&gt;
             *                     &lt;/simpleType&gt;
             *                   &lt;/element&gt;
             *                   &lt;element name="Check-Sum-Type"&gt;
             *                     &lt;simpleType&gt;
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *                         &lt;enumeration value="SHA-256"/&gt;
             *                       &lt;/restriction&gt;
             *                     &lt;/simpleType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "document"
            })
            public static class Documents {

                @XmlElement(name = "Document", required = true)
                protected List<Message.Body.Content.Documents.Document> document;

                /**
                 * Gets the value of the document property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the document property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDocument().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Message.Body.Content.Documents.Document }
                 */
                public List<Message.Body.Content.Documents.Document> getDocument() {
                    if (document == null) {
                        document = new ArrayList<Message.Body.Content.Documents.Document>();
                    }
                    return this.document;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected         content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="File-Name"&gt;
                 *           &lt;simpleType&gt;
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
                 *               &lt;maxLength value="256"/&gt;
                 *             &lt;/restriction&gt;
                 *           &lt;/simpleType&gt;
                 *         &lt;/element&gt;
                 *         &lt;element name="Content-Path"&gt;
                 *           &lt;simpleType&gt;
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
                 *               &lt;maxLength value="256"/&gt;
                 *             &lt;/restriction&gt;
                 *           &lt;/simpleType&gt;
                 *         &lt;/element&gt;
                 *         &lt;element name="Check-Sum"&gt;
                 *           &lt;simpleType&gt;
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
                 *               &lt;minLength value="64"/&gt;
                 *               &lt;maxLength value="64"/&gt;
                 *             &lt;/restriction&gt;
                 *           &lt;/simpleType&gt;
                 *         &lt;/element&gt;
                 *         &lt;element name="Check-Sum-Type"&gt;
                 *           &lt;simpleType&gt;
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
                 *               &lt;enumeration value="SHA-256"/&gt;
                 *             &lt;/restriction&gt;
                 *           &lt;/simpleType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "fileName",
                        "contentPath",
                        "checkSum",
                        "checkSumType"
                })
                public static class Document {

                    @XmlElement(name = "File-Name", required = true)
                    protected String fileName;
                    @XmlElement(name = "Content-Path", required = true)
                    protected String contentPath;
                    @XmlElement(name = "Check-Sum", required = true)
                    protected String checkSum;
                    @XmlElement(name = "Check-Sum-Type", required = true)
                    protected String checkSumType;

                    /**
                     * Gets the value of the fileName property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getFileName() {
                        return fileName;
                    }

                    /**
                     * Sets the value of the fileName property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setFileName(String value) {
                        this.fileName = value;
                    }

                    /**
                     * Gets the value of the contentPath property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getContentPath() {
                        return contentPath;
                    }

                    /**
                     * Sets the value of the contentPath property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setContentPath(String value) {
                        this.contentPath = value;
                    }

                    /**
                     * Gets the value of the checkSum property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getCheckSum() {
                        return checkSum;
                    }

                    /**
                     * Sets the value of the checkSum property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setCheckSum(String value) {
                        this.checkSum = value;
                    }

                    /**
                     * Gets the value of the checkSumType property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getCheckSumType() {
                        return checkSumType;
                    }

                    /**
                     * Sets the value of the checkSumType property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setCheckSumType(String value) {
                        this.checkSumType = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected         content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Protocol-Type"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="SXBP"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Protocol-Version"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="1"/&gt;
     *               &lt;maxInclusive value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Method"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="CONNECT"/&gt;
     *               &lt;enumeration value="FIND"/&gt;
     *               &lt;enumeration value="CREATE"/&gt;
     *               &lt;enumeration value="UPDATE"/&gt;
     *               &lt;enumeration value="DELETE"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="URI"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="256"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Status-Code"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="1"/&gt;
     *               &lt;maxInclusive value="1000"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Reason-Phrase" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Server" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Content-Encoding"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="UTF-8"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Content-Language"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="EN"/&gt;
     *               &lt;enumeration value="RU"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Content-Type"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="text/xml"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="User-Agent"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="SSC"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "protocolType",
            "protocolVersion",
            "method",
            "uri",
            "statusCode",
            "reasonPhrase",
            "server",
            "contentEncoding",
            "contentLanguage",
            "contentType",
            "userAgent"
    })
    public static class Header {

        @XmlElement(name = "Protocol-Type", required = true)
        protected String protocolType;
        @XmlElement(name = "Protocol-Version")
        protected int protocolVersion;
        @XmlElement(name = "Method", required = true)
        protected String method;
        @XmlElement(name = "URI", required = true)
        protected String uri;
        @XmlElement(name = "Status-Code")
        protected int statusCode;
        @XmlElement(name = "Reason-Phrase", required = true)
        protected String reasonPhrase;
        @XmlElement(name = "Server", required = true)
        protected String server;
        @XmlElement(name = "Content-Encoding", required = true)
        protected String contentEncoding;
        @XmlElement(name = "Content-Language", required = true)
        protected String contentLanguage;
        @XmlElement(name = "Content-Type", required = true)
        protected String contentType;
        @XmlElement(name = "User-Agent", required = true)
        protected String userAgent;

        /**
         * Gets the value of the protocolType property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getProtocolType() {
            return protocolType;
        }

        /**
         * Sets the value of the protocolType property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setProtocolType(String value) {
            this.protocolType = value;
        }

        /**
         * Gets the value of the protocolVersion property.
         */
        public int getProtocolVersion() {
            return protocolVersion;
        }

        /**
         * Sets the value of the protocolVersion property.
         */
        public void setProtocolVersion(int value) {
            this.protocolVersion = value;
        }

        /**
         * Gets the value of the method property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMethod() {
            return method;
        }

        /**
         * Sets the value of the method property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMethod(String value) {
            this.method = value;
        }

        /**
         * Gets the value of the uri property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getURI() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setURI(String value) {
            this.uri = value;
        }

        /**
         * Gets the value of the statusCode property.
         */
        public int getStatusCode() {
            return statusCode;
        }

        /**
         * Sets the value of the statusCode property.
         */
        public void setStatusCode(int value) {
            this.statusCode = value;
        }

        /**
         * Gets the value of the reasonPhrase property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getReasonPhrase() {
            return reasonPhrase;
        }

        /**
         * Sets the value of the reasonPhrase property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setReasonPhrase(String value) {
            this.reasonPhrase = value;
        }

        /**
         * Gets the value of the server property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getServer() {
            return server;
        }

        /**
         * Sets the value of the server property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setServer(String value) {
            this.server = value;
        }

        /**
         * Gets the value of the contentEncoding property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getContentEncoding() {
            return contentEncoding;
        }

        /**
         * Sets the value of the contentEncoding property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setContentEncoding(String value) {
            this.contentEncoding = value;
        }

        /**
         * Gets the value of the contentLanguage property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getContentLanguage() {
            return contentLanguage;
        }

        /**
         * Sets the value of the contentLanguage property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setContentLanguage(String value) {
            this.contentLanguage = value;
        }

        /**
         * Gets the value of the contentType property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the userAgent property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getUserAgent() {
            return userAgent;
        }

        /**
         * Sets the value of the userAgent property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setUserAgent(String value) {
            this.userAgent = value;
        }

    }

}
