//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.01.21 at 06:00:16 PM MSK 
//


package com.ediweb.education.protocol;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.ediweb.education.protocol package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ediweb.education.protocol
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Message.Body }
     */
    public Message.Body createMessageBody() {
        return new Message.Body();
    }

    /**
     * Create an instance of {@link Message.Body.Content }
     */
    public Message.Body.Content createMessageBodyContent() {
        return new Message.Body.Content();
    }

    /**
     * Create an instance of {@link Message.Body.Content.Documents }
     */
    public Message.Body.Content.Documents createMessageBodyContentDocuments() {
        return new Message.Body.Content.Documents();
    }

    /**
     * Create an instance of {@link Organization }
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link User }
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link DocumentType }
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link Route }
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link Message.Header }
     */
    public Message.Header createMessageHeader() {
        return new Message.Header();
    }

    /**
     * Create an instance of {@link Ordrsp }
     */
    public Ordrsp createOrdrsp() {
        return new Ordrsp();
    }

    /**
     * Create an instance of {@link Orders }
     */
    public Orders createOrders() {
        return new Orders();
    }

    /**
     * Create an instance of {@link DocumentStatus }
     */
    public DocumentStatus createDocumentStatus() {
        return new DocumentStatus();
    }

    /**
     * Create an instance of {@link Role }
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Message.Body.Content.Documents.Document }
     */
    public Message.Body.Content.Documents.Document createMessageBodyContentDocumentsDocument() {
        return new Message.Body.Content.Documents.Document();
    }

}
