//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.01.21 at 06:00:16 PM MSK 
//


package com.ediweb.education.protocol;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="OwnerId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SenderId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ReceiverId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "id",
        "ownerId",
        "senderId",
        "receiverId",
        "documentType"
})
@XmlRootElement(name = "Route")
public class Route {

    @XmlElement(name = "Id")
    protected int id;
    @XmlElement(name = "OwnerId")
    protected int ownerId;
    @XmlElement(name = "SenderId")
    protected int senderId;
    @XmlElement(name = "ReceiverId")
    protected int receiverId;
    @XmlElement(name = "DocumentType")
    protected int documentType;

    /**
     * Gets the value of the id property.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the ownerId property.
     *
     */
    public int getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     *
     */
    public void setOwnerId(int value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the senderId property.
     *
     */
    public int getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     *
     */
    public void setSenderId(int value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the receiverId property.
     *
     */
    public int getReceiverId() {
        return receiverId;
    }

    /**
     * Sets the value of the receiverId property.
     *
     */
    public void setReceiverId(int value) {
        this.receiverId = value;
    }

    /**
     * Gets the value of the documentType property.
     */
    public int getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     *
     */
    public void setDocumentType(int value) {
        this.documentType = value;
    }

}
