package com.ediweb.education.client.ui;

import javax.swing.*;
import java.awt.*;

/**
 * Created by rusakov on 25.11.18.
 */
public class DocCreateForm {
	private JPanel pnlMain;
	private JPanel pnlRoot;
	private JPanel pnlDoc;
	private JLabel lblDoc;
	private JTextField txt;
	private JButton btnSend;
	private JButton btnSelectDoc;
	private JPanel pnlFooter;


	public DocCreateForm() {
	}

	public JPanel getPnlMain() {
		return pnlMain;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		pnlMain = new JPanel();
		pnlMain.setLayout(new GridBagLayout());
		pnlRoot = new JPanel();
		pnlRoot.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		pnlMain.add(pnlRoot, gbc);
		pnlDoc = new JPanel();
		pnlDoc.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.insets = new Insets(5, 5, 5, 5);
		pnlRoot.add(pnlDoc, gbc);
		btnSend = new JButton();
		btnSend.setText("Отправить");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		pnlDoc.add(btnSend, gbc);
		txt = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		pnlDoc.add(txt, gbc);
		lblDoc = new JLabel();
		lblDoc.setText("Документ");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		pnlDoc.add(lblDoc, gbc);
		btnSelectDoc = new JButton();
		btnSelectDoc.setText("...");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		pnlDoc.add(btnSelectDoc, gbc);
		pnlFooter = new JPanel();
		pnlFooter.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.insets = new Insets(5, 5, 5, 5);
		pnlRoot.add(pnlFooter, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return pnlMain;
	}
}
